name: ✅Build Status Check
run-name: ✅Build Status Check (${{ github.base_ref }} branch)


on:
  pull_request:
    branches: [main, preview]


jobs:
  get_sdk_version:
    name: Get SDK Version
    runs-on: ubuntu-latest
    outputs:
      sdk-version: ${{ steps.get-sdk-version.outputs.sdk-version }}
    steps:
    - name: Get SDK Version From Environment Variable
      id: get-sdk-version
      shell: pwsh
      run: |
        "sdk-version=${{ vars.NET_SDK_VERSION }}" >> $GITHUB_OUTPUT;


  build_branch_validator:
    name: Build ${{ vars.PROJECT_NAME }} Project
    needs: get_sdk_version
    uses: KinsonDigital/Infrastructure/.github/workflows/build-csharp-project.yml@v10.0.0
    with:
      project-name: "${{ vars.PROJECT_NAME }}"
      build-config: Debug
      net-sdk-version: "${{ needs.get_sdk_version.outputs.sdk-version }}"


  build_branch_validator_shared:
    name: Build ${{ vars.PROJECT_NAME }}Shared Project
    needs: get_sdk_version
    uses: KinsonDigital/Infrastructure/.github/workflows/build-csharp-project.yml@v10.0.0
    with:
      project-name: "${{ vars.PROJECT_NAME }}Shared"
      build-config: Debug
      net-sdk-version: "${{ needs.get_sdk_version.outputs.sdk-version }}"


  build_script_generator:
    name: Build ScriptGenerator Project
    needs: get_sdk_version
    uses: KinsonDigital/Infrastructure/.github/workflows/build-csharp-project.yml@v10.0.0
    with:
      project-name: ScriptGenerator
      build-config: Debug
      net-sdk-version: "${{ needs.get_sdk_version.outputs.sdk-version }}"
      base-path: "${{ github.workspace }}/Tooling"


  build_status_check:
    name: ${{ vars.PROJECT_NAME }} Build Status Check
    needs: [build_branch_validator, build_branch_validator_shared, build_script_generator]
    runs-on: ubuntu-latest
    steps:
      - name: Print Status Check Pass Message
        shell: pwsh
        run: Write-Host "::notice::✅Build Status Check Passed✅";
